import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home ()
{
  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        <h1 className={ styles.title }>
          Welcome to my Elearning site
        </h1>

        <p className={ styles.description }>
          Get started by editing <code className={ styles.code }>pages/index.js</code>
        </p>

        <div className={ styles.grid }>
          <Link href="/learn/nextjs" className={ styles.card }>
            <h2>Learn NextJS &rarr;</h2>
          </Link>

          <Link href="/learn/react" className={ styles.card }>
            <h2>Learn React &rarr;</h2>
          </Link>

          <Link href="/learn/angular" className={ styles.card }>
            <h2>Learn Angular &rarr;</h2>
          </Link>

          <Link href="/learn/vue" className={ styles.card }>
            <h2>Learn Vue &rarr;</h2>
          </Link>
        </div>
      </main>
    </div>
  );
}
