import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import smoothieDetails from './api/smoothieDetails'
import { GetServerSideProps } from 'next';

type HomeProps = {
  recommendations: {
    id: string;
    name: string;
    description: string;
  }[];
};


export default function Home ({ recommendations }: HomeProps)
{
  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        <h1 className={ styles.title }>
          10 Ready-to-Blend Smoothie Packs
        </h1>



        <div className={ styles.grid }>
          { smoothieDetails.map((smoothie) => (
            <Link href={ `/smoothie/${smoothie.id}` } key={ smoothie.id } className={ styles.card }>
              <h2>{ smoothie.name } &rarr;</h2>
            </Link>
          )) }

        </div>
        <h2 className={ styles.recommendationsTitle }>Your Personalized Recommendations</h2>
        { recommendations && Array.isArray(recommendations) && (
          <section className={ styles.recommendationsSection }>
            { recommendations.map((smoothie) => (
              <div key={ smoothie.id } className={ styles.smoothieCard }>
                <h3 className={ styles.smoothieName }>{ smoothie.name }</h3>
                <p className={ styles.smoothieDescription }>{ smoothie.description }</p>
              </div>
            )) }
          </section>
        ) }

      </main>
    </div>
  );
}

// This function runs on the server for each request
export const getServerSideProps: GetServerSideProps = async (context) =>
{
  // Simulate fetching data based on user session, query parameters, etc.
  // For demonstration, we're returning static data
  const recommendations = [
    { id: '1', name: 'Tropical Morning', description: 'A refreshing blend of mango, pineapple, and coconut milk.' },
    // Add more recommendations as needed
  ];

  return {
    props: { // These props will be passed to the page component
      recommendations,
    },
  };
};
