import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import smoothieDetails from './api/smoothieDetails'

export default function Home ()
{
  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        <h1 className={ styles.title }>
          10 Ready-to-Blend Smoothie Packs
        </h1>

        <p className={ styles.description }>
          Get started by editing <code className={ styles.code }>pages/index.js</code>
        </p>

        <div className={ styles.grid }>
          { smoothieDetails.map((smoothie) => (
            <Link href={ `/smoothie/${smoothie.id}` } key={ smoothie.id } className={ styles.card }>
              <h2>{ smoothie.name } &rarr;</h2>
            </Link>
          )) }

        </div>
      </main>
    </div>
  );
}
